import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";
import { GlobalVars } from "src/app/global-vars";
import swal from "sweetalert2";
import { Http, RequestOptions, Headers } from "@angular/http";
import { AuthService } from "src/app/pages/login/auth.service";

@Component({
  selector: "app-customer-create-ticket",
  templateUrl: "./create-ticket.component.html",
  styleUrls: ["./create-ticket.component.css"],
})
export class CustomerCreateTicketComponent implements OnInit {
  // Form fields
  relatedService: string = "None";
  message: string = "";

  // Form state
  isSubmitting: boolean = false;
  lineCount: number = 0;
  wordCount: number = 0;

  // HTTP setup
  headers12: any;
  options: any;

  // Service/Category options
  serviceOptions = [
    { value: "None", label: "None" },
    { value: "delivery", label: "Delivery Issue" },
    { value: "payment", label: "Payment Issue" },
    { value: "product", label: "Product Question" },
    { value: "customs", label: "Customs Issue" },
    { value: "damaged", label: "Damaged Cargo" },
    { value: "lost", label: "Lost Package" },
    { value: "pricing", label: "Pricing Question" },
    { value: "tracking", label: "Tracking Issue" },
    { value: "support", label: "General Support" },
    { value: "complaint", label: "Complaint" },
    { value: "other", label: "Other" },
  ];

  constructor(
    private http: Http,
    private router: Router,
    public authService: AuthService
  ) {
    this.headers12 = new Headers({ "Content-Type": "application/json" });
    this.headers12.append("Authorization", localStorage.getItem("token"));
    this.options = new RequestOptions({ headers: this.headers12 });
  }

  ngOnInit(): void {
    // Component initialized
  }

  /**
   * Update stats for message
   */
  onMessageChange(): void {
    if (this.message) {
      const lines = this.message.split("\n").length;
      const words = this.message
        .trim()
        .split(/\s+/)
        .filter((w) => w.length > 0).length;

      this.lineCount = lines;
      this.wordCount = words;
    } else {
      this.lineCount = 0;
      this.wordCount = 0;
    }
  }

  /**
   * Submit the ticket to backend
   */
  onSubmit(): void {
    if (!this.isFormValid()) {
      swal.fire({
        icon: "warning",
        title: "Incomplete Form",
        text: "Please fill in the message field",
      });
      return;
    }

    this.isSubmitting = true;

    // Determine category from service selection
    const category =
      this.relatedService === "None" ? "support" : this.relatedService;

    // Prepare payload matching backend expectations
    const payload: any = {
      subject: this.getAutoGeneratedSubject(),
      category: category,
      priority: "Medium", // Default priority
      message_text: this.message.trim(),
    };

    this.http
      .post(GlobalVars.baseUrl + "/tickets/create", payload, this.options)
      .subscribe(
        (response) => {
          const data = response.json();
          if (data.success) {
            swal
              .fire({
                icon: "success",
                title: "Ticket Created!",
                html: `Your ticket <strong>#${data.ticket.ticket_number}</strong> has been created successfully.`,
                confirmButtonText: "OK",
              })
              .then(() => {
                // Navigate to tickets list
                this.router.navigate(["/customer/ticket-list"]);
              });
          } else {
            this.isSubmitting = false;
            swal.fire({
              icon: "error",
              title: "Error",
              text: data.message || "Failed to create ticket",
            });
          }
        },
        (error) => {
          console.error("Error creating ticket:", error);
          this.isSubmitting = false;

          if (error.status == 403) {
            this.authService.logout();
          } else {
            const errorData = error.json ? error.json() : {};
            swal.fire({
              icon: "error",
              title: "Error",
              text:
                errorData.error || "Failed to create ticket. Please try again.",
            });
          }
        }
      );
  }

  /**
   * Cancel and go back
   */
  onCancel(): void {
    if (this.hasUnsavedChanges()) {
      swal
        .fire({
          title: "Discard Changes?",
          text: "You have unsaved changes. Are you sure you want to leave?",
          icon: "warning",
          showCancelButton: true,
          confirmButtonText: "Yes, Discard",
          cancelButtonText: "No, Stay",
          confirmButtonColor: "#f44336",
        })
        .then((result) => {
          if (result.isConfirmed) {
            this.router.navigate(["/customer/ticket-list"]);
          }
        });
    } else {
      this.router.navigate(["/customer/ticket-list"]);
    }
  }

  /**
   * Check if form is valid
   */
  isFormValid(): boolean {
    return this.message.trim().length >= 10;
  }

  /**
   * Check if there are unsaved changes
   */
  hasUnsavedChanges(): boolean {
    return this.message.trim().length > 0;
  }

  /**
   * Get auto-generated subject based on service
   */
  getAutoGeneratedSubject(): string {
    const serviceObj = this.serviceOptions.find(
      (s) => s.value === this.relatedService
    );
    const serviceLabel = serviceObj ? serviceObj.label : "Support Request";

    // Truncate message for subject (first 50 chars)
    const messagePreview = this.message.trim().substring(0, 50);
    return `${serviceLabel}: ${messagePreview}${
      this.message.length > 50 ? "..." : ""
    }`;
  }

  /**
   * Get line count
   */
  getLineCount(): number {
    return this.lineCount;
  }

  /**
   * Get word count
   */
  getWordCount(): number {
    return this.wordCount;
  }
}
